"""
scripts/run_split_suite.py

Master experiment runner for split-test generalization experiments.

Calls train.py for each split strategy sequentially, collects results,
and saves a combined results table.

Each split's split_index.csv (generated by generate_splits.py) is passed as
  --split_type repo_split  --split_index outputs/splits/<name>/split_index.csv
so train.py requires no modification.

Usage:
    python scripts/run_split_suite.py --run_name split_suite_v1 --seed 42
    python scripts/run_split_suite.py --splits repo temporal cwe
    python scripts/run_split_suite.py --dry_run
    python scripts/run_split_suite.py --skip_existing --continue_on_error
"""

from __future__ import annotations

import argparse
import json
import logging
import subprocess
import sys
import time
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(Path(__file__).resolve().parent))

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-7s  %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(__name__)

ALL_SPLITS = [
    "repo", "temporal", "repo_temporal",
    "developer", "file", "function",
    "cwe", "severity",
    "hard_negative", "graph_structure", "cold_start",
]

# ── Canonical path resolution ─────────────────────────────────────────────────

def _auto_graphs_dir() -> Path | None:
    for candidate in [
        ROOT / "outputs" / "graph_ready_v2" / "graphs",
        ROOT / "outputs" / "final_graph_ready" / "graphs",
    ]:
        if candidate.exists():
            return candidate
    return None


def _auto_scaler() -> Path | None:
    for candidate in [
        ROOT / "outputs" / "graph_ready_v2" / "perrepo_scaler_v2.json",
        ROOT / "outputs" / "final_graph_ready" / "perrepo_function_scaler.json",
    ]:
        if candidate.exists():
            return candidate
    return None


# ── Build train.py command ────────────────────────────────────────────────────

def build_command(
    split_name: str,
    split_index: Path,
    run_name: str,
    output_dir: Path,
    args,
) -> list[str]:
    cmd = [
        sys.executable, str(ROOT / "scripts" / "train.py"),
        "--split_type",   "repo_split",
        "--split_index",  str(split_index),
        "--run_name",     run_name,
        "--output_dir",   str(output_dir),
        "--model",        args.model,
        "--hidden",       str(args.hidden),
        "--dropout",      str(args.dropout),
        "--epochs",       str(args.epochs),
        "--batch_size",   str(args.batch_size),
        "--lr",           str(args.lr),
        "--weight_decay", str(args.weight_decay),
        "--patience",     str(args.patience),
        "--warmup_epochs",str(args.warmup_epochs),
        "--focal_gamma",  str(args.focal_gamma),
        "--focal_alpha",  str(args.focal_alpha),
        "--seed",         str(args.seed),
        "--num_workers",  str(args.num_workers),
    ]

    if args.graphs_dir:
        cmd += ["--graphs_dir", str(args.graphs_dir)]

    if args.perrepo_norm:
        cmd.append("--perrepo_norm")
        if args.perrepo_scaler:
            cmd += ["--perrepo_scaler", str(args.perrepo_scaler)]

    if args.ablate_hunk_metrics:
        cmd.append("--ablate_hunk_metrics")
    if args.ablate_commit_merge:
        cmd.append("--ablate_commit_merge")

    return cmd


# ── Run one split ─────────────────────────────────────────────────────────────

def run_split(
    split_name: str,
    splits_dir: Path,
    output_dir: Path,
    run_prefix: str,
    args,
) -> dict:
    split_index = splits_dir / split_name / "split_index.csv"
    if not split_index.exists():
        raise FileNotFoundError(
            f"Split index not found for '{split_name}': {split_index}\n"
            f"Run: python scripts/generate_splits.py --splits {split_name}"
        )

    run_name = f"{run_prefix}_{split_name}"
    ckpt_dir = output_dir / run_name

    if args.skip_existing:
        result_path = ckpt_dir / "seed_42" / "test_results.json"
        if not result_path.exists():
            result_path = ckpt_dir / "test_results.json"
        if result_path.exists():
            logger.info("SKIP  %s (already exists: %s)", split_name, result_path)
            with open(result_path) as f:
                result = json.load(f)
            result["split_name"] = split_name
            result["status"]     = "skipped"
            return result

    cmd = build_command(split_name, split_index, run_name, output_dir, args)
    log_dir = output_dir / "logs"
    log_dir.mkdir(parents=True, exist_ok=True)
    stdout_log = log_dir / f"{run_name}.out"
    stderr_log = log_dir / f"{run_name}.err"

    logger.info("\n%s", "─" * 70)
    logger.info("RUN  %s", split_name)
    logger.info("  cmd: %s", " ".join(cmd))
    logger.info("  stdout → %s", stdout_log)

    if args.dry_run:
        logger.info("  DRY RUN — skipping")
        return {"split_name": split_name, "status": "dry_run"}

    t0 = time.time()
    with open(stdout_log, "w") as fout, open(stderr_log, "w") as ferr:
        proc = subprocess.run(cmd, stdout=fout, stderr=ferr, cwd=ROOT)

    elapsed = time.time() - t0
    logger.info("  exit=%d  elapsed=%.0fs", proc.returncode, elapsed)

    if proc.returncode != 0:
        raise RuntimeError(
            f"train.py failed for split '{split_name}' (exit {proc.returncode}). "
            f"See {stderr_log}"
        )

    # Collect result
    result: dict = {"split_name": split_name, "status": "ok", "elapsed_s": round(elapsed)}

    # Try seed subdirectory first, then top-level
    seed_dir = ckpt_dir / f"seed_{args.seed}"
    for candidate in [seed_dir / "test_results.json", ckpt_dir / "test_results.json"]:
        if candidate.exists():
            with open(candidate) as f:
                metrics = json.load(f)
            result.update(metrics)
            break

    return result


# ── Aggregate results ─────────────────────────────────────────────────────────

def save_results_table(results: list[dict], output_dir: Path, run_prefix: str) -> None:
    table_path = output_dir / f"{run_prefix}_results.csv"
    json_path  = output_dir / f"{run_prefix}_results.json"

    with open(json_path, "w") as f:
        json.dump(results, f, indent=2, default=str)

    key_metrics = ["split_name", "status", "f1", "f1_best", "auc_pr", "auc_roc", "mcc",
                   "precision", "recall", "elapsed_s"]
    rows = []
    for r in results:
        row = {k: r.get(k, "") for k in key_metrics}
        rows.append(row)

    pd.DataFrame(rows).to_csv(table_path, index=False)
    logger.info("\nResults table → %s", table_path)
    logger.info("Results JSON  → %s", json_path)

    # Print summary table
    logger.info("\n%s", "=" * 80)
    logger.info("%-25s  %6s  %6s  %6s  %6s  %6s",
                "split", "F1*", "AUC-PR", "AUC-ROC", "MCC", "status")
    logger.info("%s", "-" * 80)
    for r in results:
        logger.info(
            "%-25s  %6s  %6s  %6s  %6s  %s",
            r.get("split_name", "?"),
            f"{r.get('f1_best', ''):.4f}" if isinstance(r.get("f1_best"), float) else "",
            f"{r.get('auc_pr', ''):.4f}"  if isinstance(r.get("auc_pr"), float)  else "",
            f"{r.get('auc_roc', ''):.4f}" if isinstance(r.get("auc_roc"), float) else "",
            f"{r.get('mcc', ''):.4f}"     if isinstance(r.get("mcc"), float)     else "",
            r.get("status", ""),
        )


# ── Argument parsing ──────────────────────────────────────────────────────────

def parse_args():
    p = argparse.ArgumentParser(description="Run all split-test experiments")

    # Which splits
    p.add_argument("--splits", nargs="+", default=ALL_SPLITS, choices=ALL_SPLITS,
                   help="Which splits to run (default: all)")

    # Paths
    p.add_argument("--splits_dir", default=None,
                   help="Directory containing generated splits (default: outputs/splits)")
    p.add_argument("--output_dir", default=None,
                   help="Checkpoint output directory (default: checkpoints)")
    p.add_argument("--graphs_dir", default=None,
                   help="Override graphs directory")
    p.add_argument("--perrepo_scaler", default=None,
                   help="Override per-repo scaler JSON path")

    # Run naming
    p.add_argument("--run_name", default="split_suite",
                   help="Prefix for run names: <run_name>_<split_name>")

    # Model (mirrors train.py defaults / protocol)
    p.add_argument("--model",          default="sage", choices=["sage", "rgcn", "mlp"])
    p.add_argument("--hidden",         type=int,   default=128)
    p.add_argument("--dropout",        type=float, default=0.5)
    p.add_argument("--epochs",         type=int,   default=60)
    p.add_argument("--batch_size",     type=int,   default=128)
    p.add_argument("--lr",             type=float, default=1e-3)
    p.add_argument("--weight_decay",   type=float, default=2e-3)
    p.add_argument("--patience",       type=int,   default=10)
    p.add_argument("--warmup_epochs",  type=int,   default=3)
    p.add_argument("--focal_gamma",    type=float, default=1.5)
    p.add_argument("--focal_alpha",    type=float, default=0.65)
    p.add_argument("--seed",           type=int,   default=42)
    p.add_argument("--num_workers",    type=int,   default=4)

    # Normalization / ablations (match final protocol)
    p.add_argument("--perrepo_norm",       action="store_true", default=True)
    p.add_argument("--no_perrepo_norm",    action="store_false", dest="perrepo_norm")
    p.add_argument("--ablate_hunk_metrics", action="store_true", default=True)
    p.add_argument("--ablate_commit_merge", action="store_true", default=True)

    # Runner control
    p.add_argument("--dry_run",          action="store_true")
    p.add_argument("--skip_existing",    action="store_true")
    p.add_argument("--continue_on_error", action="store_true")

    return p.parse_args()


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    args = parse_args()

    splits_dir = Path(args.splits_dir) if args.splits_dir else ROOT / "outputs" / "splits"
    output_dir = Path(args.output_dir) if args.output_dir else ROOT / "checkpoints"

    # Auto-detect paths
    if not args.graphs_dir:
        gd = _auto_graphs_dir()
        if gd:
            args.graphs_dir = str(gd)
            logger.info("Auto-detected graphs_dir: %s", gd)

    if not args.perrepo_scaler and args.perrepo_norm:
        sc = _auto_scaler()
        if sc:
            args.perrepo_scaler = str(sc)
            logger.info("Auto-detected perrepo_scaler: %s", sc)

    output_dir.mkdir(parents=True, exist_ok=True)

    logger.info("Split suite: %d splits to run", len(args.splits))
    logger.info("splits_dir : %s", splits_dir)
    logger.info("output_dir : %s", output_dir)
    logger.info("run_prefix : %s", args.run_name)
    logger.info("dry_run    : %s", args.dry_run)

    all_results: list[dict] = []
    n_ok, n_fail = 0, 0

    for split_name in args.splits:
        try:
            result = run_split(
                split_name, splits_dir, output_dir, args.run_name, args
            )
            all_results.append(result)
            n_ok += 1
        except Exception as exc:
            logger.error("FAILED: %s — %s", split_name, exc, exc_info=True)
            all_results.append({
                "split_name": split_name,
                "status": "failed",
                "error": str(exc),
            })
            n_fail += 1
            if not args.continue_on_error:
                logger.error("Stopping (--continue_on_error not set)")
                break

    save_results_table(all_results, output_dir, args.run_name)

    logger.info("\nFinished: %d ok  %d failed", n_ok, n_fail)
    if n_fail and not args.dry_run:
        sys.exit(1)


if __name__ == "__main__":
    main()
