name: thesis
channels:
  - conda-forge
dependencies:
  - ipykernel
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - polars
  - pyarrow
  - python=3.11
  - rich
  - scikit-learn
  - tqdm
  - scipy
  - xgboost
  - shap
  - tqdm
  - pip
  - pip:
      - torch
      - torchvision
