name: thesis
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - jupyterlab
  - matplotlib
  - "numpy<2.0"
  - pandas
  - polars
  - pyarrow
  - rich
  - scikit-learn
  - "scipy<2.0"
  - xgboost
  - shap
  - seaborn
  - tqdm
  - pip:
      - torch
      - torchvision
      - torchaudio
      - torch-geometric